# Generated by Django 3.1.3 on 2020-11-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('status', models.CharField(choices=[('In progress', 'Work in Progress'), ('Not done', 'Work are not done yet'), ('Done', 'Problem are solved')], default='Not done', max_length=200)),
                ('issues', models.CharField(default='No Issues', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('status', models.CharField(choices=[('In progress', 'Work in Progress'), ('Not done', 'Work are not done yet'), ('Done', 'Problem are solved')], default='Not done', max_length=200)),
                ('issues', models.CharField(default='No Issues', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('status', models.CharField(choices=[('In progress', 'Work in Progress'), ('Not done', 'Work are not done yet'), ('Done', 'Problem are solved')], default='Not done', max_length=200)),
                ('issues', models.CharField(default='No Issues', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
